create database ss2_convert_erd_to_db;
use ss2_convert_erd_to_db;

CREATE TABLE PHIEUXUAT (
    SoPX VARCHAR(20) PRIMARY KEY,
    NgayXuat DATE
);

CREATE TABLE PHIEUNHAP (
    SoPN VARCHAR(20) PRIMARY KEY,
    NgayNhap DATE
);

CREATE TABLE VATTU (
    MaVTU VARCHAR(20) PRIMARY KEY,
    TenVTU VARCHAR(100),
    DGNhap DECIMAL(10,2),
    SLNhap INT
);

CREATE TABLE DONHANG (
    SoDH VARCHAR(20) PRIMARY KEY,
    NgayDH DATE
);

CREATE TABLE NHACC (
    MaNCC VARCHAR(20) PRIMARY KEY,
    TenNCC VARCHAR(100),
    DiaChi VARCHAR(255),
    SĐT VARCHAR(15)
);

CREATE TABLE CHITIET_PHIEUXUAT (
    SoPX VARCHAR(20),
    MaVTU VARCHAR(20),
    DGXuat DECIMAL(10,2),
    SLXuat INT,
    PRIMARY KEY (SoPX, MaVTU),
    FOREIGN KEY (SoPX) REFERENCES PHIEUXUAT(SoPX),
    FOREIGN KEY (MaVTU) REFERENCES VATTU(MaVTU)
);

CREATE TABLE CHITIET_PHIEUNHAP (
    SoPN VARCHAR(20),
    MaVTU VARCHAR(20),
    SLNhap INT,
    PRIMARY KEY (SoPN, MaVTU),
    FOREIGN KEY (SoPN) REFERENCES PHIEUNHAP(SoPN),
    FOREIGN KEY (MaVTU) REFERENCES VATTU(MaVTU)
);

CREATE TABLE CHITIET_DONHANG (
    SoDH VARCHAR(20),
    MaVTU VARCHAR(20),
    PRIMARY KEY (SoDH, MaVTU),
    FOREIGN KEY (SoDH) REFERENCES DONHANG(SoDH),
    FOREIGN KEY (MaVTU) REFERENCES VATTU(MaVTU)
);

CREATE TABLE CUNG_CAP (
    MaNCC VARCHAR(20),
    MaVTU VARCHAR(20),
    PRIMARY KEY (MaNCC, MaVTU),
    FOREIGN KEY (MaNCC) REFERENCES NHACC(MaNCC),
    FOREIGN KEY (MaVTU) REFERENCES VATTU(MaVTU)
);